name: CI Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build test environment
        run: docker build -t test-env .

      - name: Run lint check
        run: docker run --rm test-env npm run lint

      - name: Run format check
        run: docker run --rm test-env npm run format:check

      - name: Run build test
        run: docker run --rm test-env npm run build
