# CI/CD 部署到 Azure Static Web Apps
name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [main]
  pull_request:
    branches: [main] # 新增：PR时也运行CI检查

jobs:
  # CI 阶段：测试
  test:
    name: Run Tests and Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 构建测试镜像
        run: docker build -t test-env .

      - name: 运行 ESLint 代码检查
        run: docker run --rm test-env npm run lint

      - name: 运行 Prettier 格式检查
        run: docker run --rm test-env npm run format:check

      # - name: 运行单元测试
      #   run: docker run --rm test-env npm test

  # CD 阶段：部署到 Azure (只在main分支运行)
  build_and_deploy:
    name: Build and Deploy to Azure
    needs: test
    runs-on: ubuntu-latest
    # 重要：只在push到main时部署，PR时不部署
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      # 部署到 Azure Static Web Apps
      - name: 构建并部署到 Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: '/'
          output_location: 'dist'
          app_build_command: 'npm run build'
