# CI/CD 部署到 Azure Static Web Apps
name: Deploy to Azure Static Web Apps

on:
  push:
    branches: [main]

jobs:
  # CI 阶段：测试
  test:
    name: Run Tests and Code Quality Checks # 添加清晰的名字
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 构建测试镜像
        run: docker build -t test-env .

      - name: 运行 ESLint 代码检查
        run: docker run --rm test-env npm run lint

      - name: 运行 Prettier 格式检查
        run: docker run --rm test-env npm run format:check

      # - name: 运行单元测试
      #   run: docker run --rm test-env npm test

  # CD 阶段：部署到 Azure
  build_and_deploy:
    name: Build and Deploy to Azure # 更清晰的名字
    needs: test # 依赖测试通过
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      # 部署到 Azure Static Web Apps
      - name: 构建并部署到 Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: 'upload'
          app_location: '/' # 源代码位置
          output_location: 'dist' # 构建输出目录
          app_build_command: 'npm run build' # 构建命令
